### ISSUE TITLE
Nutzungshinweis

### ISSUE THREAD

**Issue by isospin** [olien/scss_compiler#1]
Wie kann ich das ins Template einbinden?

**Comment by olien** [comment]
Sofern der Compiler aktiv ist wird der automatisch geladen und ausgeführt.

Pfade

./assets/scss/styles.scss
./assets/scss/print.scss
./assets/css/

Wenn die Pfade stimmen kannst Du die css Dateien wie folgt laden:

```
<link rel="stylesheet" href="/assets/css/styles.min.css" type="text/css" media="screen,print" />
<link rel="stylesheet" href="/assets/css/print.min.css" type="text/css" media="print" />
```

**Comment by isospin** [comment]
ok ganz einfach die dateien im ordner assets/css verlinken! kein snippet fürs template. da stand ich wohl auf dem schlauch... funktioniert jetzt.

aber wie funktioniert das bei sass mit den @imports (z.b. von mixins oder normalize)?
@import "grid.scss" wird genauso in die min.css übernommen. ich möchte aber, das das kompiliert wird. hast du da einen tipp?

**Comment by olien** [comment]
Meine styles.scss sieht ungefähr so aus:

```
@import "scss/mixins/all";
@import "scss/project/vars";

// Hier die "normalen" SCSS Angaben
* {
  border: 1px solid lightgrey;
}


// am Ende der Datei
@import "scss/responsive";

```

die **_all.scss** im Ordner **/assets/scss/mixins/** könnte so aussehen:

```
@import "base",
"bootstrap_grid",
"background",
"border",
"center",
"filter",
"gradient",
"prefixer",
"seohelper",
"transform",
"transition",
"translucent",
"unset";
```

---

In deinem Beispiel müsste die die Datei grid.scss ja besser _grid.scss heissen und so importiert werden: @import "grid" (sofern der Pfad stimmt).

---

Meine Verzeichnisse sehen so aus:

![unbenannt-6](https://cloud.githubusercontent.com/assets/330516/13464451/99855244-e091-11e5-972c-051521d0576c.png)

**Comment by AWqxKAWERbXo** [comment]
Danke für die Erläuterung! Das gehört unbedingt in die Hilfe zum Addon aufgenommen oder zumindest ein Link zu diesem Beitrag.

**Comment by olien** [comment]
Ist in der nächsten Version enthalten.
