### ISSUE TITLE
Compass hinzufügen

### ISSUE THREAD

**Issue by eaCe** [olien/scss_compiler#2]
Ich arbeite viel mit Compass, vielleicht könnte man das hier mit einbinden...

https://github.com/leafo/scssphp-compass

**Comment by olien** [comment]
Verstehe ich das richtig, dass es reichen würde die Compass SCSS Dateien zu importieren?
Wenn ja ist das - für mich - keine Funktion des Addons. Wenn nicht korrigiere mich bitte.

Dann könnte ja auch z.B.: Bootstrap und Susy mit "rein"... oder?
So etwas könne ich mir als Plugin vorstellen....
