### ISSUE TITLE
SCSS im Backend benutzen. How-to?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [olien/scss_compiler#3]
Ich würde gerne Anpassungen im Backend mit SCSS vornehmen und dafür den SCSS-Compiler benutzen. Ich frage eigentlich ungern nach einer Lösung auf dem Silbertablett, aber da ich nicht weiß, wo ich anfangen soll: Wie gehe ich da vor?

(Der Plan ist auch, dass meine als Module organisierten SCSS-Dateien fürs Frontend auch im Backend inkludiert werden, um das gleiche Layout wie im Frontend auch in den einzelnen Blöcken in der Strukturansicht zu haben.)

**Comment by olien** [comment]
Hm. Eigentlich ist das hier wirklich nur fürs Frontend gedacht.
Ansonsten hätte ich ja den Backend SCSS Compiler fürs Frontend genommen :-))

Vielleicht hat @tbaddade eine Idee?

**Comment by tbaddade** [comment]
Wegen Backend, schau dir das [redaxo PlugIn](https://github.com/redaxo/redaxo/tree/master/redaxo/src/addons/be_style/plugins/redaxo) an. Das macht nichts anderes.

Wegen den Frontend-Styles. Hier würde ich im Projektaddon die kompilierten Dateien in das Backend einbinden.

**Comment by AWqxKAWERbXo** [comment]
Merci

**Comment by olien** [comment]
ISt erledigt - oder? Ansonsten neu aufmachen.

**Comment by AWqxKAWERbXo** [comment]
Ist gerade eine Krücke, weil die Pfade nicht relativ zur CSS-Datei gesetzt werden, aber funktioniert.
