### ISSUE TITLE
Fatal error: Class 'scssc' not found - nach Update auf Redaxo 5.2 beta

### ISSUE THREAD

**Issue by isospin** [olien/scss_compiler#4]
Fatal error: Class 'scssc' not found - nach Update auf Redaxo 5.2 beta

**Comment by olien** [comment]
Finde den Fehler leider nicht ....:-(

**Comment by phoebusryan** [comment]
@isospin Wo genau (Welches File, welche Zeile) wird der Error ausgelöst?

**Comment by olien** [comment]
Ich glaube am zuverlässigsten erscheint der Fehler bei dem Aufruf der History im Backend. 
Vermute hier einen Fehler in den Pfadangaben...

**Comment by phoebusryan** [comment]
Bindest du das denn manuell ein? Eigentlich gäbs da ja den autoloader.

**Comment by isospin** [comment]
"ErrorException" thrown in /is/htdocs/.../www/temp/......de/redaxo/src/addons/scss_compiler/vendor/scss_compiler.php on line 71
Fatal error: Class 'scssc' not found

**Comment by olien** [comment]
wie geht das mit dem autoloader?

**Comment by phoebusryan** [comment]
Es heisst "autoloader" weil er automatisch lädt. Du musst nichts machen :)

Bzgl. dem Fehler: Dafür weiss ich zu wenig über das Addon. Wie funktioniert es? Wie definiert man, was compiliert werden soll etc? Wo wird compiliert?

**Comment by isospin** [comment]
ich fasse mal kurz zusammen, so wie ich das bis jetzt verstanden habe: 
das scss-compiler  addon hat die scssc klasse gar nicht selbst an bord, sondern hat sie 'mitgenutzt'. die war anscheinend in be_style vorhanden, das scssphp an bord hat. 
in rex 5.2 wurde in be_style auch scssphp auf den aktuellen stand gebracht und es scheint das es in scssphp 0.6.5 die klasse scssc nicht mehr gibt.

**Comment by olien** [comment]
Nein. Ich hab die extra reingeldaden ... und leider null Zeit mir das richtig anzugucken.
Vorurlaubsstress zum Urlaub ohne Rechner...

**Comment by isospin** [comment]
ok. gar kein problem. wünsche dir einen schönen urlaub!
ich forsch mal weiter mit meinem halbwissen und dokumentier das mal hier..

ich komm da nur drauf weil, wenn ich be_style in rex5.1 deaktiviere fliegt der gleiche fehler...

**Comment by isospin** [comment]
ich habe für mich erstmal folgende lösung gefunden:

den vendor ordner habe ich kompletto gelöscht. 
und die boot.php wie folgt ersetzt:

```
if (!rex::isBackend()) {
   if ($this->getConfig('scss_compiler_aktiv') == '1') {
        $compiler = new rex_scss_compiler();
        $compiler->setScssFile('./assets/scss/styles.scss');
        $compiler->setCssFile('./assets/css/styles.min.css');
        $compiler->compile();
   }
}
```

im meinem .scss file musste ich dann nur noch die @import pfade anpassen.

**Comment by olien** [comment]
Top. Wenn ich das schaffe werde ich das hier so übernehmen! Danke!

**Comment by phoebusryan** [comment]
@isospin Woher nimmt er den SCSS-Compiler wenn du den Vendor-Ordner löschst? Wäre das dann der aus dem Core? Gibt es den noch?

**Comment by isospin** [comment]
der scss compiler wird im be_style addon verwendet um das css für das backend zu generieren.

**Comment by isospin** [comment]
das scss-compiler addon hat vorher anscheinend auch die klasse aus dem be_style verwendet, da die eigene vermutlich nicht 'wirksam' eingebunden war (wenn ich in rex 5.1 be_style deaktiviere produziert das scss-compiler addon auch den fehler)

**Comment by phoebusryan** [comment]
Okay, soweit nachvollziehbar. Dann fragt sich aber, ob das Addon überhaupt notwendig ist. Wenn es 1. eh nur noch aus der boot.php besteht und zweitens nur Komponenten benutzt, die ohnehin schon da sind.... oder?

**Comment by olien** [comment]
ja. dann könnte es eigentlich weg und wir könnten irgendwo im wiki beschrieben wie man fürs frontent scss files kompilieren kann - oder?

würde ja ins project addon passen....

**Comment by isospin** [comment]
mit dieser basic funktionalität wäre es wirklich überflüssig. man kann die vier zeilen auch ins template schreiben...

was allerdings bei dieser minimallösung nicht schön ist, das man in seinem scss file die @import pfade 'aufs backend' einstellen muß:

```
@import "./assets/scss/import/normalize";  
@import "./assets/scss/import/baseline";
@import "./assets/scss/import/grid";  
```

prinzipiell wäre also ein addon, das die pfade hinbiegt und z.b. einen umschalter für `compressed` und `not compressed` hat schon ganz praktisch, weil intuitiver als im wiki nachschauen und 'falsche' import pfade in scss zu verwenden.

was meint ihr?

**Comment by olien** [comment]
also hier einfach entschlacken?

**Comment by AWqxKAWERbXo** [comment]
Also ich kann den Fehler bestätigen. 

Wäre sehr dankbar über eine Kurzanleitung, wie ich das über "projects" das SCSS selbst parsen kann, weil's gerade eilt und revanchiere mich mit einer ausführlichen YForm-Doku zum Table Manager ;D

**Comment by isospin** [comment]
ich hab mir erstmal die diese zeilen ins template gepackt:

```
        $compiler = new rex_scss_compiler();
        $compiler->setScssFile('./assets/scss/styles.scss');
        $compiler->setCssFile('./assets/css/styles.min.css');
        $compiler->compile();
```

und die @import-pfade in meiner styles.scss angepasst:

`@import "scss/import/normalize";`
zu
`@import "./assets/scss/import/normalize";`

**Comment by AWqxKAWERbXo** [comment]
Danke!

Hab das jetzt selbst ausprobiert und finde das eigentlich eine super Idee, den scss-compiler so weit zu entschlacken, dass man wirklich nicht mehr hat als eine Einstellungsseite:
1. Mit der Möglichkeit, dem Compiler zu aktivieren und zu deaktivieren (sonst werden ja ständig neue CSS-Dateien generiert)
2. Mit der Möglichkeit, anzugeben, welche SCSS-Dateien überwacht und in welchen Zielpfad geparst werden soll.

**Comment by olien** [comment]
Mag mich jemand damit überraschen wenn ich aus dem urlaub zurück komme? :-)

**Comment by AWqxKAWERbXo** [comment]
Wenn es darum geht, was zu veröffentlichen, das zumindest dem Update auf Redaxo 5.2 stand hält, dann wäre das mein PR dazu. Fehlt nur noch in der ReadMe eine Info zu den Pfaden.

Das hat mich schon bei 4.x enttäuscht, wenn zu einem Update die Addons komplett kaputt gegangen sind - so wäre zumindest was da.

**Comment by phoebusryan** [comment]
Statistik: +8 −11,583 Glückwunsch 💃 

Ich würde aber aufgrund des BCs unbedingt auf Version 2.0. Ansonsten sieht es gut aus.

**Comment by AWqxKAWERbXo** [comment]
Wenn du mir hilfst, das mit den import-Pfaden zu fixen und Code für 1-2 Input-Felder auf der Einstellungsseite für die Eingabe mehrerer SCSS-Dateien stellst, dann pass ich die boot.php noch an, dass alle angegebenen SCSS-Dateien durchlaufen werden.

Hatte mich gerade versucht, am PHP-Mailer zu orientieren, dort werden die Input-Felder auf der Einstellungsseite allerdings noch von Hand gesetzt - das geht doch mittlerweile auch einfacher.

**Comment by AWqxKAWERbXo** [comment]
btw.: Muss da nicht noch ne Abhängigkeit vom be_style-Addon definiert werden oder wie ist das?

**Comment by phoebusryan** [comment]
Ja, diese müsste definitiv in die package.yml

**Comment by olien** [comment]
PR vertrauensvoll übernommen :-). Zu mehr komme ich gerade leider nicht!

**Comment by olien** [comment]
Ist erledigt - oder? Ansonsten neu aufmachen.

**Comment by tbaddade** [comment]
Ist das mit den import Pfaden noch aktuell und die Methode `setRootDir()`hat nicht weitergeholfen?

Das mit `not compressed`und `compressed`  kann man über die Methode `setFormatter` einstellen.

[Diese Formatter sind dabei](https://github.com/leafo/scssphp/tree/0649d38dfef6808be1a89040a3312e8bda0b3aed/src/Formatter) und müssten so übergeben werden:

`$compiler->setFormatter('Leafo\ScssPhp\Formatter\Datei');`
Bsp.:
`$compiler->setFormatter('Leafo\ScssPhp\Formatter\Expanded');`

**Comment by AWqxKAWERbXo** [comment]
Ja, war noch aktuell. Danke, die Info hat mir gefehlt.

**Comment by AWqxKAWERbXo** [comment]
Zu bedenken ist, dass jede SCSS-Datei im Zweifel bei jedem Aufruf (ggf. auch jedem Frontend-Aufruf) neu generiert wird. Von daher war die Checkbox "Compiler aktiv" schon eine tolle Sache. Von daher hat das Addon (oder als Plugin von minify) schon seine Berechtigung. 

Besser wäre es jedoch, wenn eine automatische Erkennung nach Änderungen der scss-Datei (einschließlich includierter SCSS-Dateien!) vorgenommen würde. Gab's die nicht auch mal in diverses SCSS-Compilern?

(SEO42 konnte das mal *duck-und-weg*)

/cc @polarpixel

**Comment by phoebusryan** [comment]
Alter.. SEO42. Ich kanns nicht mehr hören. Aber eine automatische Änderungserkennung ist easy zu implementieren. Minify hat dies auch schon drin.

**Comment by olien** [comment]
Hey das wäre total klasse. Leider komme ich immer noch zu nichts (Rechner noch nicht aufgebaut).
Das ist ein FOR Addon und jeder kann - sehr gerne - helfen :-))

LG
Oliver
