### ISSUE TITLE
@include SCSS-Dateien auch kompilieren

### ISSUE THREAD

**Issue by bega011** [olien/scss_compiler#8]
Es wäre super, wenn der Compiler in der kompilierenden Datei (styles.scss) auch die inkludierten SCSS-Dateien berücksichtigen/kompilieren würde.
Z.B. im Bootstrap braucht man oft nur die gewünschten Komponeneten nach Bedarf zu laden.

**Comment by olien** [comment]
Hm. Das funktioniert doch.
Wie sind denn deine Pfade?

In meiner styles.scss steht

@import "scss/01-mixins/_all";
@import "scss/02-page/_all";
@import "scss/03-components/_all";
@import "scss/04-vendor/_all";

Die styles.scc liegt im Ordner assets/scss/

**Comment by bega011** [comment]
Komisch. bei mir hats nicht funktioniert. Es wurde zwar eine .css-Datei erstellt, aber da drin waren nur Includes-Pfade drin, theoretisch wie die styles.scss 1:1
Meine Pfade sind so:

@import "utilities";
@import "custom";
@import „magnific-popup";

usw.

**Comment by bega011** [comment]
Du meinst ich müsste den absoluten Pfad angeben?

So:
@import „scss/utilities“;
@import „scss/custom“;
@import „scss/magnific-popup“;

**Comment by olien** [comment]
Probiers mal

**Comment by bega011** [comment]
Klappt nicht. Das ist der inhalt der styles.min.css:
@import "scss/variables";@import "scss/mixins";@import "scss/fonts"; ... usw

**Comment by olien** [comment]
und die Datei variables heisst

_variables.scss

?

**Comment by bega011** [comment]
genau. Muss ich auch den Unterstrich und Sufix .scss angeben?

**Comment by olien** [comment]
Ja

**Comment by bega011** [comment]
Ohje. Mixins includieren wiederum andere SCSS-Dateien. Bei denen auch alles umschreiben?

**Comment by olien** [comment]
Ich kenne das gar nicht anders....

https://github.com/twbs/bootstrap-sass
https://github.com/twbs/bootstrap/tree/v4-dev/scss

**Comment by bega011** [comment]
Naja, SCSS-Compiler erkennt automatisch, dass das eine scss-Datei ist, ohne Unterstrich und Sufix. Schau mal z.B. in diese Datei bootstrap.scss:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/bootstrap.scss

Da sind alle Importe ohne Unterstrich und Sufix. Normalerweise funktioniert das einwandfrei.

**Comment by olien** [comment]
Hm. Dann guck doch mal wie die Dateiname der Dateien aussehen...

z.B.:

_breadcrumb.scss
_button-group.scss
_buttons.scss
_card.scss
_carousel.scss
_close.scss
_code.scss
_custom-forms.scss
_custom.scss

Ich glaub ich hab die gerade falsch verstanden. Ich inkludiere die Dateien so:

@import „scss/utilities“;
@import „scss/custom“;
@import „scss/magnific-popup“;

ohne Suffix und Unterstrich...

**Comment by bega011** [comment]
Genau, habs vorhin auch so inkludiert, es klappt einfach nicht, es wird nichts kompiliert. Und die Ladezeit der Seite wird dabei extrem lang. Irgendwie funktioniert es nicht.

**Comment by olien** [comment]
hm. muss grad mal passen...

**Comment by bega011** [comment]
Naja, jetzt habe ich es gelöscht und über Installer wieder instaliert und jetzt wird der folgende Fehler im Frontend gefeurt: 

"Error" thrown in /html/redaxo/src/addons/scss_compiler/vendor/scss_compiler.php on line 71
Class 'scssc' not found

#0 /html/redaxo/src/addons/scss_compiler/vendor/scss_compiler.php(135): scss_compiler->compile()
#1 /html/redaxo/src/addons/scss_compiler/boot.php(5): include_once('/html/redaxo/sr...')
#2 /html/redaxo/src/core/lib/packages/package.php(228): include('/html/redaxo/sr...')
#3 /html/redaxo/src/core/packages.php(55): rex_package->includeFile('boot.php')
#4 /html/redaxo/src/core/frontend.php(12): include_once('/html/redaxo/sr...')
#5 /html/redaxo/src/core/boot.php(105): require('/html/redaxo/sr...')
#6 /html/index.php(9): require('/html/redaxo/sr...')
#7 {main}

**Comment by olien** [comment]
Nimm mal die Version aus dem Git bitte

**Comment by bega011** [comment]
Die hatte ich zuerst, mit der hats nicht funktioniert.

**Comment by olien** [comment]
hm. hab keine idee mehr....

**Comment by bega011** [comment]
Naja, ok, trotzdem danke.

**Comment by bega011** [comment]
Also Oli, das Problem war die Inkompatibilität der scssphp (Compiler.php) mit der Bootstrap 4 Alpha Version wenn die Dateien noch weitere Dateien includieren. Hier ist der Patch:
https://github.com/leafo/scssphp/compare/master...FMCorz:issue-446

Jetzt funktioniert super.

**Comment by olien** [comment]
Danke. Baue ich später ein...

**Comment by olien** [comment]
Somit an dieser Stelle erledigt...
